### ISSUE TITLE
High memory usage when the worker is updating data

### ISSUE THREAD

**Issue by Rylon** [SpringerPE/cf-light-api#4]
The implementation with the Parallel gem uses multiple child processes, but because there are several levels of maps running within each other, and we're specifying 4 processes at each level, we're actually spawning something like 4x4x4 processes, each with it's own copy of the original process memory.

As a result, memory requirements are unnecessarily large when the worker is updating data, this needs to be addressed in a future release.

**Comment by simonjohansson** [comment]
This is fixes with the use of threads instead of spawning new processes.

https://github.com/SpringerPE/cf-light-api/commit/59cd6185ced1f5d36cffbe48d04cb80caedde1dc

**Comment by Rylon** [comment]
Nice one, thanks @simonjohansson. I had issues initially when trying threads, which is why I went for processes, so I'm glad it works now!
