### ISSUE TITLE
bundle exec cf_light_api starts worker even when CF credentials haven't been set

### ISSUE THREAD

**Issue by TomShacham** [SpringerPE/cf-light-api#8]
The README tells us to set the following environment vars

export CF_API=https://api.cf.yourdomain.com
export CF_USER=username
export CF_PASSWORD=password

but even if you don't, the cf_light_api worker still starts up

[outputFromWorker.txt](https://github.com/SpringerPE/cf-light-api/files/31809/outputFromWorker.txt)

**Comment by Rylon** [comment]
@TomShacham forgot to look at this! I'll put a fix in place tomorrow, thanks for reporting!
